variables:
  PROJECT_NAME: "Otus.Teaching.PromoCodeFactory.UnitTests"
  BUILD_IMAGE: "mcr.microsoft.com/dotnet/core/sdk:3.1"
  RUNTIME_IMAGE: "mcr.microsoft.com/dotnet/core/aspnet:3.1.1-alpine3.10"

stages:
- build
- test
- docker

build:
stage: build
image: $BUILD_IMAGE
only:
  - master
script:
  - cd src/$PROJECT_NAME
  - dotnet restore --interactive
  - dotnet build --configuration Release
  - dotnet publish --configuration Release --output ../../publish/
artifacts:
  paths:
    - ./publish/*
  expire_in: 1 week
tags:
- docker

test:
stage: test
image: $BUILD_IMAGE
only:
  - master
script:
  - cd src/$PROJECT_NAME
  - dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=../../UnitTestResult.xml"
artifacts:
  paths:
    - ./UnitTestResult.xml
  reports:
    junit: ./UnitTestResult.xml
tags:
- docker

docker:
stage: docker
image: docker:stable
services:
  - docker:dind
only:
  - develop
before_script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
script:
  - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest src
  - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
after_script:
  - docker logout ${CI_REGISTRY}
tags:
- docker